/**
 * GraphQL fragment for CustomComponent.
 * Define the necessary fields for the component.
 */
fragment {{ componentName }}Fragment on {{ componentName }} {
  id
  name
  // Additional GraphQL fields here
}
