/**
 * Generated TypeScript file from {{ componentName }} GraphQL fragment.
 * This file is automatically generated and should be included in your build process.
 */
// Import the generated fragment here
export const {{ componentName }}Name = '{{ componentName }}';
