/**
 * Generated TypeScript file from CustomComponent GraphQL fragment.
 * This file is automatically generated and should be included in your build process.
 */
// Import the generated fragment here
export const customComponentName = 'CustomComponent';
